name:                petri-app-land
version:             0.1.12.2
github:              "cschank/petri-app-land"
license:             BSD3
author:              "Christopher William Schankula"
maintainer:          "schankuc@mcmaster.ca"
copyright:           "2018-2019 Christopher William Schankula, Christopher Anand"

extra-source-files:
- Readme.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cschank/petri-app-land#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- time
- filepath
- directory
- process
- ansi-terminal
- aeson
- zip-archive
- http-conduit


library:
  source-dirs: src
  ghc-options:
    -Wincomplete-patterns

executables:
  petri-app-land-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wincomplete-patterns
    dependencies:
    - petri-app-land

tests:
  petri-app-land-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - petri-app-land
